services:
  rdgen:
    # use bryangerlach/rdgen:latest for the latest build
    #build: .
    image: bryangerlach/rdgen:latest
    restart: unless-stopped
    environment:
      SECRET_KEY: "c3f963abb96f42981d234f3f6790ba07f290755a4af8fa002ad820f3dafec0c9dbd5f9e1208da3b3a746861a6673ce83f85997f1756ab8bab28df42d56633383909588bcc552d4052576877573d2dbec257690303fcd96f908ecaade841d8bf10aa86437"
      GHUSER: "khat17"
      GHBEARER: "github_access_token"
      GENURL: "accessible_url_of_server"
      ZIP_PASSWORD: ""
      GHBRANCH: "master"
      PROTOCOL: "https"
      REPONAME: "rdgen"
      SH_SECRET: ""
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
    volumes:
      - ./exe:/opt/rdgen/exe
      - ./png:/opt/rdgen/png
      - ./temp_zips:/opt/rdgen/temp_zips
